image: python:3.10

stages:
  - static_check
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --with tests
  - source .venv/bin/activate

pre_commit:
  stage: static_check
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

## deploy
pages:
  # push the latest documentation of the main branch to the Gitlab pages.
  # available at https://cps.pages.gitlab.lrz.de/commonroad/automatic-scenario-labeling
  stage: deploy
  # when: manual
  only:
    - dev
  publish: site
  script:
    - poetry install --with docs
    - mkdocs build
  artifacts:
    paths:
      - site
  environment:
    name: Gitlab Pages
    url: https://cps.pages.gitlab.lrz.de/commonroad/automatic-scenario-labeling
